Allow using real city names when available
Marak/faker.js pull request #1106
Opened 2021-02-12 09:20 UTC by vulcaryn

2021-02-13 15:07 UTC, Marak requested changes

2021-02-17 09:13 UTC, vulcaryn commented on lib/address.js
> +    return faker.random.arrayElement(faker.definitions.address.city_name);
It's the same thing for all properties not defined in a language like `state_abbr` in French for instance.

2021-02-17 19:53 UTC, Marak commented on lib/address.js
> +    return faker.random.arrayElement(faker.definitions.address.city_name);
@vulcaryn - That is good point, but since we have fallback functionality it will always go to `en` for default definitions so we don't get error or undefined.

I think we need to add some `en` cities in `./en/address/city_names.js` for this to work.

I do want to get this merged.

2021-02-19 01:48 UTC, Marak commented
I pushed city names for `en` locale with https://github.com/Marak/faker.js/commit/50c1693c3ffbc976c802152089683f3f86de6154

This should be enough to get this merged.

2021-02-19 02:55 UTC, merged

2021-02-19 02:55 UTC, Marak commented
Thank you for your contributions @vulcaryn 

Merged!