Give each faker instance its own random number generator
Marak/faker.js pull request #1147
Opened 2021-03-24 14:24 UTC by cowboyd

> fixes #768 

Currently, every Faker instance shares the same random number generator instance which means that to seed one faker instance is to seed them all. This is also a pre-requisite for #318 (see https://github.com/Marak/faker.js/issues/318#issuecomment-369658181)

This just extracts the public API of the mersenne twister found in `vendor/mersenne.js` and creates a single instance of it per faker.

This implementation is a tad sub-optimal since calling `seed()` on a faker instance will result in two redundant calls to `mersenne.init_genrand()`: one in `random.js` and the other in `datatype.js`. It would probably be more DRY to create the mersenne instance once in faker and then pass it into to the `Random` and `Datatype` instances, however, this takes the strategy of the smallest possible API change.

2021-03-24 21:25 UTC, Marak requested changes

2021-03-24 21:25 UTC, Marak commented on lib/mersenne.js
> +  gen.init_genrand((new Date).getTime() % 1000000000);
Can we now remove these lines from ./vendor/mersenne` now? We shouldn't be too worried about backwards compatible for this.

2021-03-24 21:25 UTC, Marak commented
Thank you for your contributions @cowboyd 

Please see code review.

We should be able to get this merged quickly.

2021-03-25 08:09 UTC, cowboyd commented on lib/mersenne.js
> +  gen.init_genrand((new Date).getTime() % 1000000000);
Done!

2021-03-25 08:14 UTC, cowboyd commented
@Marak Removed the old api from `vendor/mersenne.js` with minimal impact. Is there a changelog I should update?

2021-03-25 18:46 UTC, merged

2021-03-25 18:48 UTC, Marak commented
Looks good to me @cowboyd 

Merged.

Please let us know if you find anything else we can improve.

Thanks again!

2021-03-25 19:55 UTC, cowboyd commented
Nice! 🙌🏻 🙌🏻 🙌🏻 

Glad to help out where I can...

2021-03-25 20:12 UTC, cowboyd commented
@Marak Oh yeah, one thing I was curious about is what the release cadence is?

2021-03-25 21:27 UTC, Marak commented
Hrmm, the browser build seems to be failing now. I think it's related to this.

Investigating.

<img width="879" alt="Screen Shot 2021-03-25 at 5 27 11 PM" src="https://user-images.githubusercontent.com/70011/112546089-60df0380-8d8f-11eb-9257-d86535fef614.png">

2021-03-25 21:33 UTC, Marak commented
Should be resolved with a patch to the examples https://github.com/Marak/faker.js/commit/fac3164beb08d2eb175bb980e9821e36be8464af

Doesn't seem like it should be in issue in core