Add Arabic Date
Marak/faker.js pull request #933
Opened 2020-07-16 15:03 UTC by F-xobj

2020-08-06 02:26 UTC, Marak commented
@F-xobj -

Thank you for your contribution.

I don't really speak Arabic. Could we get another person who speaks the language to confirm these commits?

I checked the Git history and think @thaerlabs or @anas-qa can assist.

2020-08-06 07:19 UTC, F-xobj commented
> @F-xobj -
> 
> Thank you for your contribution.
> 
> I don't really speak Arabic. Could we get another person who speaks the language to confirm these commits?
> 
> I checked the Git history and think @thaerlabs or @anas-qa can assist.

Sure . will be happy if they see it .  @thaerlabs ,@anas-qa  can you please confirm these changes ?
if all is good , i will add more commits . 
Thanks all .

2020-10-04 11:42 UTC, naderalfakesh requested changes
Hi 
Just fix these three typos and I can give approve feedback. 
I am a native speaker. 
Best regards...

2020-10-04 11:42 UTC, naderalfakesh commented on lib/locales/ar/address/state.js
> +  "مشق",
Please change "مشق", into "دمشق",

2020-10-04 11:42 UTC, naderalfakesh commented on lib/locales/ar/address/state.js
> +  "ير الزور",
Please change   "ير الزور", into 
  "دير الزور",

2020-10-04 11:42 UTC, naderalfakesh commented on lib/locales/ar/address/state.js
> +  "لحسكة",
"لحسكة",
ino 
"الحسكة",

2020-11-25 21:57 UTC, F-xobj commented
@naderalfakesh can you re-review again, thanks!

2020-12-16 08:11 UTC, fityanos commented
@F-xobj LGTM 🎯

2021-02-09 04:37 UTC, merged

2021-02-09 04:38 UTC, Marak commented
Thank you for your contributions @F-xobj and @fityanos and @naderalfakesh 

Merged.